### ISSUE TITLE
single, double, and quad procedures

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/quadpack#5]
What is the best way to export single, double, and quad procedures that:

 * is standard fortran
 * doesn't duplicate code
 * doesn't break IDEs, linters, syntax highlighters
 * is backward compatible with the old interface (e.g, qag for single, dqag for double)
 * is able to be documented with Ford without confusion or duplicated routines in the docs

See #4

**Comment by jacobwilliams** [comment]
The solution that uses:

```fortran
#if defined(EXPORT_REAL)
    ! export the single precision names (qag, etc.)
    generic, public :: qag => dqag
    generic, public :: qage => dqage
...
```

Works with fort, but not Gfortran. I think this may be a Fortran 2018 feature?

**Comment by jacobwilliams** [comment]
Fixed in #4

**Comment by ivan-pi** [comment]
For the quad procedures, don't you need to (re)generate the weights of the Gauss-Kronrod quadrature with higher precision?
According to the comments in the original source code:

```fortran
        ! gauss quadrature weights and kronrod quadrature abscissae and weights
        ! as evaluated with 80 decimal digit arithmetic by l. w. fullerton,
        ! bell labs, nov. 1981.
```

I'm not sure what 80-decimal digit arithmetic means exactly; do they mean 80-bit extended precision? The Wikipedia page on [quad precision](https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format) states:

> The IEEE 754 standard specifies a binary128 as having:
>
> * Sign bit: 1 bit
> * Exponent width: 15 bits
> * Significand precision: 113 bits (112 explicitly stored)
>
> _This gives from 33 to 36 significant decimal digits precision. [emphasis added]_ If a decimal string with at most 33 significant digits is converted to IEEE 754 quadruple-precision representation, and then converted back to a decimal string with the same number of digits, the final result should match the original string. If an IEEE 754 quadruple-precision number is converted to a decimal string with at least 36 significant digits, and then converted back to quadruple-precision representation, the final result must match the original number.

The current implementation provides the constants with 33 decimal digits (presumably all of which are correct?), however a few significant digits might be missing for the quad implementation.

The QUADPACK manual (Piessens et al., 1983, pg. 7) contains the paragraph:

> In the single precision QUADPACK version, these constants are given to 16 figures. Two double precision versions are supplied with constants given to 16 or to 33 figures. With a few exceptions, the mathematically correct values are irrational and thus the tabulated data are only approximations. The formulae which use this data are thus incapable of providing accurate results to more than, say, 16 or 33 places even for a very simple integrand. This then, becomes a fundamental limitation of virtually all the QUADPACK routines.

There are some coefficient-based tests to verify the adequacy of a quadrature formula, see

> Walter Gautschi, How and how not to check Gaussian quadrature formulae, _Bit_ 23, 1983, 209-216. https://www.cs.purdue.edu/homes/wxg/selected_works/section_08/084.pdf

Alternatively, we could verify their precision by comparison with the results from numerical integration with [arbitrary-precision ball arithmetic (Arb)](https://fredrikj.net/blog/2017/11/new-rigorous-numerical-integration-in-arb/).

**Comment by jacobwilliams** [comment]
Yes, we need to see about regenerating them with more precision. I haven't looked into it yet. I can open a new issue for that.
