### ISSUE TITLE
Regenerate coefficients with more precision for quad precision version

### ISSUE THREAD

**Issue by jacobwilliams** [jacobwilliams/quadpack#6]
See #5. Maybe we need 36 digits?

**Comment by jacobwilliams** [comment]
See also: https://www.advanpix.com/2011/11/07/gauss-kronrod-quadrature-nodes-weights/

**Comment by jacobwilliams** [comment]
I have the code now to generate them with more precision. All except for the ones in `dqng`, which I don't quite understand yet.

For the other, I will commit the updated values.

**Comment by jacobwilliams** [comment]
Code here: https://github.com/jacobwilliams/kronrod

**Comment by jacobwilliams** [comment]
For the Patterson ones in `dqng`, perhaps [this code](https://github.com/aakash30jan/JohnBurkardt-F90Bank/blob/c9ccac6c2a60fe1d892ab2e9c46e67e796dfeff3/people.sc.fsu.edu/_jburkardt/f_src/patterson_rule_compute/patterson_rule_compute.f90) can be used?

**Comment by crimus** [comment]
Actually, the right code is [this](https://people.math.sc.edu/Burkardt/f_src/toms672/toms672.html), but it has to be modified to get more precision, available only in Fortran90 [here](https://people.math.sc.edu/Burkardt/f_src/toms672/toms672.f90). I was searching hardly to find this, and once I've found it, i thought it will be nice help someone that was struggling as me. 

Cristiano
